apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistics_manage
  labels:
    app: logistics_manage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logistics_manage
  template:
    metadata:
      labels:
        app: logistics_manage
    spec:
      containers:
        - name: logistics_manage
          image: username/logistics_manage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5